from datetime import datetime
from flaskblog import db, login_manager, app
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"
    
class BalanceSheet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Integer, nullable=False)

    bs01 = db.Column(db.Integer, nullable=False)
    bs02 = db.Column(db.Integer, nullable=False)
    bs03 = db.Column(db.Integer, nullable=False)
    bs04 = db.Column(db.Integer, nullable=False)
    bs05 = db.Column(db.Integer, nullable=False)
    bs06 = db.Column(db.Integer, nullable=False)
    bs08 = db.Column(db.Integer, nullable=False)
    bs08 = db.Column(db.Integer, nullable=False)
    bs09 = db.Column(db.Integer, nullable=False)
    bs10 = db.Column(db.Integer, nullable=False)
    bs11 = db.Column(db.Integer, nullable=False)
    bs12 = db.Column(db.Integer, nullable=False)
    bs13 = db.Column(db.Integer, nullable=False)
    bs14 = db.Column(db.Integer, nullable=False)
    bs15 = db.Column(db.Integer, nullable=False)
    bs16 = db.Column(db.Integer, nullable=False)
    bs17 = db.Column(db.Integer, nullable=False)
    bs18 = db.Column(db.Integer, nullable=False)
    bs19 = db.Column(db.Integer, nullable=False)
    bs20 = db.Column(db.Integer, nullable=False)
    bs21 = db.Column(db.Integer, nullable=False)
    bs22 = db.Column(db.Integer, nullable=False)
    bs23 = db.Column(db.Integer, nullable=False)


class IncomeStatement(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Integer, nullable=False)

    is01 = db.Column(db.Integer, nullable=False)
    is02 = db.Column(db.Integer, nullable=False)
    is03 = db.Column(db.Integer, nullable=False)
    is04 = db.Column(db.Integer, nullable=False)
    is05 = db.Column(db.Integer, nullable=False)
    is06 = db.Column(db.Integer, nullable=False)
    is08 = db.Column(db.Integer, nullable=False)
    is08 = db.Column(db.Integer, nullable=False)
    is09 = db.Column(db.Integer, nullable=False)
    is10 = db.Column(db.Integer, nullable=False)
    is11 = db.Column(db.Integer, nullable=False)
    is12 = db.Column(db.Integer, nullable=False)
    is13 = db.Column(db.Integer, nullable=False)
    is14 = db.Column(db.Integer, nullable=False)
    is15 = db.Column(db.Integer, nullable=False)
    is16 = db.Column(db.Integer, nullable=False)
    is17 = db.Column(db.Integer, nullable=False)
    is18 = db.Column(db.Integer, nullable=False)
    is19 = db.Column(db.Integer, nullable=False)
    is20 = db.Column(db.Integer, nullable=False)
    is21 = db.Column(db.Integer, nullable=False)
    is22 = db.Column(db.Integer, nullable=False)
    is23 = db.Column(db.Integer, nullable=False)
    is24 = db.Column(db.Integer, nullable=False)
    is25 = db.Column(db.Integer, nullable=False)
    is26 = db.Column(db.Integer, nullable=False)
    is27 = db.Column(db.Integer, nullable=False)
    is28 = db.Column(db.Integer, nullable=False)
    is29 = db.Column(db.Integer, nullable=False)
    is30 = db.Column(db.Integer, nullable=False)
    is31 = db.Column(db.Integer, nullable=False)
    is32 = db.Column(db.Integer, nullable=False)
    is33 = db.Column(db.Integer, nullable=False)
    is34 = db.Column(db.Integer, nullable=False)
    is35 = db.Column(db.Integer, nullable=False)
    is36 = db.Column(db.Integer, nullable=False)
    is37 = db.Column(db.Integer, nullable=False)
    is38 = db.Column(db.Integer, nullable=False)
    is39 = db.Column(db.Integer, nullable=False)
    is40 = db.Column(db.Integer, nullable=False)
    is41 = db.Column(db.Integer, nullable=False)
    is42 = db.Column(db.Integer, nullable=False)
    is43 = db.Column(db.Integer, nullable=False)
    is44 = db.Column(db.Integer, nullable=False)

class CashFlow(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Integer, nullable=False)

    cf01 = db.Column(db.Integer, nullable=False)
    cf02 = db.Column(db.Integer, nullable=False)
    cf03 = db.Column(db.Integer, nullable=False)
    cf04 = db.Column(db.Integer, nullable=False)
    cf05 = db.Column(db.Integer, nullable=False)
    cf06 = db.Column(db.Integer, nullable=False)
    cf08 = db.Column(db.Integer, nullable=False)
    cf08 = db.Column(db.Integer, nullable=False)
    cf09 = db.Column(db.Integer, nullable=False)
    cf10 = db.Column(db.Integer, nullable=False)
    cf11 = db.Column(db.Integer, nullable=False)
    cf12 = db.Column(db.Integer, nullable=False)
    cf13 = db.Column(db.Integer, nullable=False)
    cf14 = db.Column(db.Integer, nullable=False)
    cf15 = db.Column(db.Integer, nullable=False)
    cf16 = db.Column(db.Integer, nullable=False)
    cf17 = db.Column(db.Integer, nullable=False)
    cf18 = db.Column(db.Integer, nullable=False)
    cf19 = db.Column(db.Integer, nullable=False)
    cf20 = db.Column(db.Integer, nullable=False)
    cf21 = db.Column(db.Integer, nullable=False)
    cf22 = db.Column(db.Integer, nullable=False)
    cf23 = db.Column(db.Integer, nullable=False)
    cf24 = db.Column(db.Integer, nullable=False)
    cf25 = db.Column(db.Integer, nullable=False)
    cf26 = db.Column(db.Integer, nullable=False)
    cf27 = db.Column(db.Integer, nullable=False)
    cf28 = db.Column(db.Integer, nullable=False)
    cf29 = db.Column(db.Integer, nullable=False)
    cf30 = db.Column(db.Integer, nullable=False)
    cf31 = db.Column(db.Integer, nullable=False)
    cf32 = db.Column(db.Integer, nullable=False)
    cf33 = db.Column(db.Integer, nullable=False)
    cf34 = db.Column(db.Integer, nullable=False)
    cf35 = db.Column(db.Integer, nullable=False)
    cf36 = db.Column(db.Integer, nullable=False)
    cf37 = db.Column(db.Integer, nullable=False)
    cf38 = db.Column(db.Integer, nullable=False)
    cf39 = db.Column(db.Integer, nullable=False)
    cf40 = db.Column(db.Integer, nullable=False)
    cf41 = db.Column(db.Integer, nullable=False)
    cf42 = db.Column(db.Integer, nullable=False)
    cf43 = db.Column(db.Integer, nullable=False)

class ConsolidatedBalanceSheet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Integer, nullable=False)

    cbs01 = db.Column(db.Integer, nullable=False)
    cbs02 = db.Column(db.Integer, nullable=False)
    cbs03 = db.Column(db.Integer, nullable=False)
    cbs04 = db.Column(db.Integer, nullable=False)
    cbs05 = db.Column(db.Integer, nullable=False)
    cbs06 = db.Column(db.Integer, nullable=False)
    cbs08 = db.Column(db.Integer, nullable=False)
    cbs08 = db.Column(db.Integer, nullable=False)
    cbs09 = db.Column(db.Integer, nullable=False)
    cbs10 = db.Column(db.Integer, nullable=False)
    cbs11 = db.Column(db.Integer, nullable=False)
    cbs12 = db.Column(db.Integer, nullable=False)
    cbs13 = db.Column(db.Integer, nullable=False)
    cbs14 = db.Column(db.Integer, nullable=False)
    cbs15 = db.Column(db.Integer, nullable=False)
    cbs16 = db.Column(db.Integer, nullable=False)
    cbs17 = db.Column(db.Integer, nullable=False)
    cbs18 = db.Column(db.Integer, nullable=False)
    cbs19 = db.Column(db.Integer, nullable=False)
    cbs20 = db.Column(db.Integer, nullable=False)
    cbs21 = db.Column(db.Integer, nullable=False)
    cbs22 = db.Column(db.Integer, nullable=False)
    cbs23 = db.Column(db.Integer, nullable=False)
    cbs24 = db.Column(db.Integer, nullable=False)
    cbs25 = db.Column(db.Integer, nullable=False)
    cbs26 = db.Column(db.Integer, nullable=False)
    cbs27 = db.Column(db.Integer, nullable=False)
    cbs28 = db.Column(db.Integer, nullable=False)

class ConsolidatedIncomeStatement(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Integer, nullable=False)

    cis01 = db.Column(db.Integer, nullable=False)
    cis02 = db.Column(db.Integer, nullable=False)
    cis03 = db.Column(db.Integer, nullable=False)
    cis04 = db.Column(db.Integer, nullable=False)
    cis05 = db.Column(db.Integer, nullable=False)
    cis06 = db.Column(db.Integer, nullable=False)
    cis08 = db.Column(db.Integer, nullable=False)
    cis08 = db.Column(db.Integer, nullable=False)
    cis09 = db.Column(db.Integer, nullable=False)
    cis10 = db.Column(db.Integer, nullable=False)
    cis11 = db.Column(db.Integer, nullable=False)
    cis12 = db.Column(db.Integer, nullable=False)
    cis13 = db.Column(db.Integer, nullable=False)
    cis14 = db.Column(db.Integer, nullable=False)
    cis15 = db.Column(db.Integer, nullable=False)
    cis16 = db.Column(db.Integer, nullable=False)
    cis17 = db.Column(db.Integer, nullable=False)
    cis18 = db.Column(db.Integer, nullable=False)
    cis19 = db.Column(db.Integer, nullable=False)
    cis20 = db.Column(db.Integer, nullable=False)
    cis21 = db.Column(db.Integer, nullable=False)
    cis22 = db.Column(db.Integer, nullable=False)
    cis23 = db.Column(db.Integer, nullable=False)
    cis24 = db.Column(db.Integer, nullable=False)
    cis25 = db.Column(db.Integer, nullable=False)
    cis26 = db.Column(db.Integer, nullable=False)
    cis27 = db.Column(db.Integer, nullable=False)
    cis28 = db.Column(db.Integer, nullable=False)
    cis29 = db.Column(db.Integer, nullable=False)
    cis30 = db.Column(db.Integer, nullable=False)
    cis31 = db.Column(db.Integer, nullable=False)
    cis32 = db.Column(db.Integer, nullable=False)
    cis33 = db.Column(db.Integer, nullable=False)
    cis34 = db.Column(db.Integer, nullable=False)
    cis35 = db.Column(db.Integer, nullable=False)
    cis36 = db.Column(db.Integer, nullable=False)
    cis37 = db.Column(db.Integer, nullable=False)
    cis38 = db.Column(db.Integer, nullable=False)
    cis39 = db.Column(db.Integer, nullable=False)
    cis40 = db.Column(db.Integer, nullable=False)
    cis41 = db.Column(db.Integer, nullable=False)
    cis42 = db.Column(db.Integer, nullable=False)
    cis43 = db.Column(db.Integer, nullable=False)
    cis44 = db.Column(db.Integer, nullable=False)
    cis45 = db.Column(db.Integer, nullable=False)
    cis46 = db.Column(db.Integer, nullable=False)
    cis47 = db.Column(db.Integer, nullable=False)
    cis48 = db.Column(db.Integer, nullable=False)
    cis49 = db.Column(db.Integer, nullable=False)
    cis50 = db.Column(db.Integer, nullable=False)

# class ConsolidatedCashFlow(db.Model):
#     pass


with app.app_context():
    db.create_all()
